# Generated by Django 5.0 on 2023-12-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafty', '0002_remove_product_id_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
